name = "treksistem-api"
main = "apps/api/dist/index.js"
compatibility_date = "2024-05-30"

[vars]
# Placeholder for future environment variables

# D1 Database binding for local development and remote deployment
[[d1_databases]]
binding = "DB"
database_name = "treksistem-db-local"
database_id = "132903a7-4ca2-40a6-8900-a43fd0a89da4"
migrations_dir = "packages/db/migrations"