name = "treksistem-api"
main = "apps/api/dist/index.js"
compatibility_date = "2024-05-30"

[vars]
# Placeholder for future environment variables

# D1 Database binding for local development and remote deployment
[[d1_databases]]
binding = "DB"
database_name = "treksistem-db-local"
database_id = "local-dev-db"