name = "treksistem-api"
main = "apps/api/dist/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# External dependencies for bundling
[build]
command = ""

[vars]
# Auth configuration
GOOGLE_REDIRECT_URI = "http://localhost:8787/api/auth/callback/google"
# Test values for verification (replace with real values in production)
GOOGLE_CLIENT_ID = "test-client-id.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "test-client-secret"
JWT_SECRET = "test-jwt-secret-32-characters-long-string-for-verification"
R2_PUBLIC_URL = "https://pub-your-r2-public-url.r2.dev"
UPLOAD_URL_EXPIRES_IN_SECONDS = "300"

[secrets]
R2_ACCOUNT_ID = ""
R2_ACCESS_KEY_ID = ""
R2_SECRET_ACCESS_KEY = ""

# D1 Database binding for local development and remote deployment
[[d1_databases]]
binding = "DB"
database_name = "treksistem-db-local"
database_id = "132903a7-4ca2-40a6-8900-a43fd0a89da4"
migrations_dir = "packages/db/migrations"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "treksistem-prod-report-photos"
preview_bucket_name = "treksistem-dev-report-photos"

# Cron triggers
[triggers]
crons = ["0 0 1 * *"]  # Monthly invoice generation on the 1st at midnight UTC